export const GET_MODEL_LIST_SUCCESS ="GET_MODEL_LIST_SUCCESS"
export const GET_MODEL_LIST_FAILURE = "GET_MODEL_LIST_FAILURE"
export const GET_MODEL_BY_BRAND_LIST_SUCCESS ="GET_MODEL_BY_BRAND_LIST_SUCCESS"
export const GET_MODEL_BY_BRAND_LIST_FAILURE = "GET_MODEL_BY_BRAND_LIST_FAILURE"